@startuml

abstract class Правило {
  + код: Integer
  + тип правила: String
  + условие: String
  + описание: String
  + начало действия: Date
  + конец действия: Date
  + фишки: Integer
}

class Правило_по_операции {
  + мин.сумма: Double
  + мин.операций: Double
  + тип операции: String
}

class Правило_по_дате {
  + дата: String
  + признак даты: Boolean
}

class Участник_программы {
  + email: String
  + пароль: String
  + ФИО: String
  + дата рождения: Date
  + количество фишек: Integer
}

class Карта_лояльности {
  + номер: Integer
  + баланс: Double {derived}
  + блокирована: Boolean
}

class Операция {
  + номер: Integer
  + дата: Date
  + сумма: Double
  + тип операции: Enum
}

class Вознаграждение {
  + номер: Integer
  + дата: Date
  + использовано: Boolean
}

class Вид_вознаграждения {
  + код: Integer
  + название: String
  + описание: String
}

Правило <|-- Правило_по_операции
Правило <|-- Правило_по_дате

Участник_программы "1" -- "1..*" Карта_лояльности
Карта_лояльности "1" -- "1..*" Операция
Участник_программы "1" -- "1..*" Вознаграждение
Правило "1" -- "1..*" Вознаграждение
Вид_вознаграждения "1" -- "1..*" Вознаграждение

@enduml